### PR TITLE
fix: insert then cancel with workspace selected

### LINKED ISSUE #623: Insert block then cancel via escape (during move) doesn't remove the block if the workspace was selected
1. Select the workspace via "W"
2. "T", choose any block
3. Escape to cancel
4. Note the block stays as if you confirmed it

With any other initial cursor position this removes the block that hasn't had its position confirmed.

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Fixes https://github.com/google/blockly-keyboard-experimentation/issues/623

The implementation conflated having no insertStartPosition with the block being new. But when the workspace is selected then there is no insert start position even if the block is new. Instead track whether we're inserting or just moving separately.

Demo: https://fix-ws-insert-cancel.blockly-keyboard-experimentation.pages.dev/

### CODE REVIEW

File: src/actions/mover.ts [hunk 1]
```diff
@@ -229,7 +242,7 @@ export class Mover {
       info.startLocation,
     );
 
-    if (dragStrategy.isNewBlock && target) {
+    if (dragStrategy.moveType && target) {
```
Comment (microbit-matt-hillsdon) [inline src/actions/mover.ts]: Whoops

**Comment by microbit-matt-hillsdon** [comment]
Fixed conflicts (just test imports).

**Comment by microbit-matt-hillsdon** [comment]
This will conflict with #626.

My preference is for you to merge the approved #626 first and then I'll fix the conflicts here again which I've already done once on an integration branch.

**Comment by maribethb** [comment]
> This will conflict with #626.
> 
> My preference is for you to merge the approved #626 first and then I'll fix the conflicts here again which I've already done once on an integration branch.

This is #626, which PR did you mean to comment this on and which one did you want us to actually merge first?

**Comment by microbit-matt-hillsdon** [comment]
> This is #626, which PR did you mean to comment this on and which one did you want us to actually merge first?

Whoops! #625 I think, which also changes the mover code. Happy either way, just trying to save effort.

**Review by RoboErikG — APPROVED** [review]
Got it and I see #625 is already in. Sorry for the delay, I was out last week. I can merge once the conflicts are resolved.

This looks good for kb-exp, though I'm going to file a bug for us to rethink the mover APIs before this gets merged into Core as this feels a bit messy. Let us know if you have any suggestions!

**Comment by microbit-matt-hillsdon** [comment]
Something else to ponder at the same time is scenarios like #635.

Conflicts fixed, please consider this an unsolicited ad for [git rerere](https://git-scm.com/book/en/v2/Git-Tools-Rerere).

```bash
➜  blockly-keyboard-experimentation git:(fix-ws-insert-cancel) ✗ git merge main
...
Resolved 'src/actions/move.ts' using previous resolution.
Resolved 'src/actions/mover.ts' using previous resolution.
...
```
